### PR TITLE
Improved XMI Attribute Processing and Printing

### LINKED ISSUE #15: Parsing Multiple Instances in an XMI File
The XMI parser fails to parse an XMI file that contains multiple instances in the same resource.  The parser returns TypeError: Cannot read property 'eClass' of undefined in 'onopentag'. This is essentially the XMI version of Pull Request #4. We have constructed a potential solution and will submit after testing is complete.

### PR DESCRIPTION
**Pull request by cfi-dphillips**
This pull request Resolves #15 , #16, and #17.  Tests were also created to test for the issues when appropriate.

### CODE REVIEW

**Comment by ghillairet** [comment]
Thanks, I can't look at it right now, I will do next week.

**Comment by ghillairet** [comment]
@cfi-dphillips I would rather support uuids like it is done for ids in JSON, see my changes made from your branch https://github.com/emfjson/ecore.js/pull/20/commits/94c72c3753c96cef4e157cca81a5f15575b48472

**Comment by cfi-dphillips** [comment]
Thanks!  Our first attempt was based on some of the logic in the Eclipse code, but we like this solution better.  We have integrated and tested this with no significant issues.  This also resolved getting the id into the JSON version of the resource as well.  Thanks again.

**Comment by ghillairet** [comment]
Great so I'll release those changes.

**Comment by cfi-dphillips** [comment]
I believe that this merge resolves #16, #17, and #18.

**Pull request merged**
